from __future__ import annotations


FIELD_MAPPING = {
    "gesamtbetrag": [
        "gesamtbetrag",
        "total",
        "summe",
        "betrag",
        "endbetrag",
        "gesamtsumme",
        "rechnungsbetrag",
        "brutto gesamt",
        "amount due",
        "to pay",
        "gesamt",
        "rechnungssumme",
        "nettobetrag",
        "bruttobetrag",
    ],
    "rechnungsnummer": [
        "rechnungsnr",
        "re-nr",
        "rechnung nr",
        "invoice no",
        "invoice number",
        "rechnungsnummer",
        "belegnummer",
        "dokumentnummer",
        "nr.",
        "re.nr.",
    ],
    "datum": [
        "datum",
        "date",
        "rechnungsdatum",
        "ausstellungsdatum",
        "belegdatum",
        "vom",
        "erstellt am",
        "invoice date",
        "leistungsdatum",
    ],
    "faelligkeitsdatum": [
        "fällig",
        "fälligkeitsdatum",
        "zahlbar bis",
        "due date",
        "zahlungsziel",
        "zu zahlen bis",
    ],
    "mwst_betrag": [
        "mwst",
        "mehrwertsteuer",
        "ust",
        "umsatzsteuer",
        "vat",
        "tax",
        "steuer",
        "19%",
        "7%",
        "mwst-betrag",
    ],
    "menge": ["menge", "anzahl", "qty", "quantity", "stück", "stk", "amount"],
    "einzelpreis": [
        "einzelpreis",
        "ep",
        "preis",
        "price",
        "unit price",
        "stückpreis",
        "ep netto",
        "einzelwert",
    ],
    "gesamtpreis": [
        "gesamtpreis",
        "gp",
        "gesamt",
        "total",
        "gp netto",
        "zeilenbetrag",
        "positionsbetrag",
        "line total",
    ],
    "beschreibung": [
        "beschreibung",
        "bezeichnung",
        "artikel",
        "leistung",
        "position",
        "bezeichng",
        "description",
        "item",
        "produkt",
        "service",
    ],
    "artikelnummer": [
        "artikelnr",
        "art-nr",
        "artikel-nr",
        "item no",
        "artnr",
        "artikelnummer",
        "sku",
        "produktnummer",
    ],
    "lieferant": [
        "lieferant",
        "vendor",
        "supplier",
        "absender",
        "von",
        "from",
        "rechnungssteller",
        "auftragnehmer",
    ],
    "kunde": [
        "kunde",
        "customer",
        "empfänger",
        "an",
        "to",
        "rechnungsempfänger",
        "auftraggeber",
        "käufer",
    ],
}


REVERSE_FIELD_MAPPING = {
    synonym.lower().strip(): target
    for target, synonyms in FIELD_MAPPING.items()
    for synonym in synonyms
}
